Update exit-wo-annotation.yml

diff --git a/.github/workflows/exit-wo-annotation.yml b/.github/workflows/exit-wo-annotation.yml
--- a/.github/workflows/exit-wo-annotation.yml
+++ b/.github/workflows/exit-wo-annotation.yml
@@ -11,4 +11,4 @@ jobs:
     steps:
 
     - name: exit with status 1
-      run: exit 1
+      run: exit 1 || echo "Action Failed"
